export const endpoints = {
  health: '/health',
  auth: {
    superAdminStatus: '/api/v1/admin/auth/super-admin/status',
    superAdmin: '/api/v1/admin/auth/super-admin',
    login: '/api/v1/admin/auth/login',
    refresh: '/api/v1/admin/auth/refresh',
    logout: '/api/v1/admin/auth/logout',
    me: '/api/v1/admin/auth/me',
    changePassword: '/api/v1/admin/auth/change-password',
    twoFactor: '/api/v1/admin/auth/two-factor',
    permissions: '/api/v1/admin/auth/permissions',
    team: '/api/v1/admin/auth/team',
    teamMember: (id: string) => `/api/v1/admin/auth/team/${id}`,
  },
  dashboard: '/api/v1/admin/dashboard',
  orders: '/api/v1/admin/orders',
  order: (id: string) => `/api/v1/admin/orders/${id}`,
  orderStatus: (id: string) => `/api/v1/admin/orders/${id}/status`,
  orderNotes: (id: string) => `/api/v1/admin/orders/${id}/notes`,
  orderRefund: (id: string) => `/api/v1/admin/orders/${id}/refund`,
  orderBulk: '/api/v1/admin/orders/bulk',
  products: '/api/v1/admin/products',
  product: (id: string) => `/api/v1/admin/products/${id}`,
  productImages: (id: string) => `/api/v1/admin/products/${id}/images`,
  productBulkStatus: '/api/v1/admin/products/bulk/status',
  customers: '/api/v1/admin/customers',
  customer: (id: string) => `/api/v1/admin/customers/${id}`,
  customerBlock: (id: string) => `/api/v1/admin/customers/${id}/block`,
  customerNotes: (id: string) => `/api/v1/admin/customers/${id}/notes`,
  inventory: '/api/v1/admin/inventory',
  inventoryHistory: '/api/v1/admin/inventory/history',
  productInventoryHistory: (id: string) => `/api/v1/admin/inventory/${id}/history`,
  inventoryRestock: (id: string) => `/api/v1/admin/inventory/${id}/restock`,
  inventoryAdjust: (id: string) => `/api/v1/admin/inventory/${id}/adjust`,
  analytics: '/api/v1/admin/analytics',
  analyticsExport: '/api/v1/admin/analytics/export',
  notifications: {
    settings: '/api/v1/admin/notifications/settings',
    event: (eventType: string) => `/api/v1/admin/notifications/settings/${eventType}`,
    history: '/api/v1/admin/notifications/history',
    readAll: '/api/v1/admin/notifications/history/read-all',
    read: (id: string) => `/api/v1/admin/notifications/history/${id}/read`,
  },
  settings: {
    all: '/api/v1/admin/settings',
    store: '/api/v1/admin/settings/store',
    storeLogo: '/api/v1/admin/settings/store/logo',
    payments: '/api/v1/admin/settings/payments',
    paymentGateway: (gateway: string) => `/api/v1/admin/settings/payments/${gateway}`,
    shipping: '/api/v1/admin/settings/shipping',
    export: '/api/v1/admin/settings/export',
  },
};
