import { useNavigate, useParams } from 'react-router-dom';
import { ChevronDown, Mail, MapPin, Send } from 'lucide-react';
import { useStore } from '../../data/store';
import adminPfp from '../../assets/admin-pfp.png';
export function CustomerDetailPage(){
 const navigate=useNavigate(),{customerId}=useParams(),{data}=useStore(); const customer=data.customers.find(c=>c.id===decodeURIComponent(customerId||'')); if(!customer)return <main><section className="card empty"><h1>Customer not found</h1></section></main>;
 const orders=data.orders.filter(o=>o.customerId===customer.id); return <main className="figma-page customer-detail-figma"><section className="card customer-hero"><div className="customer-avatar-photo"><img src={adminPfp} alt=""/></div><div className="customer-hero-copy"><h1>{customer.name}</h1><p><Mail/>{customer.email}<span>▣ Joined Oct 2022</span></p><div><span className="vip-chip">VIP CUSTOMER</span><span className="active-chip">ACTIVE</span></div></div><button className="customer-actions">Actions <ChevronDown/></button></section>
 <div className="customer-grid"><section className="card order-history"><div className="customer-section-head"><h2>▤ Order History</h2><button className="bare linkish" onClick={()=>navigate('/orders')}>View All</button></div><table><thead><tr><th>ORDER ID</th><th>DATE</th><th>STATUS</th><th className="number">TOTAL</th></tr></thead><tbody>{orders.length?orders.map(o=><tr key={o.id}><td className="mono">#{o.id}</td><td>{new Date(o.date).toLocaleDateString()}</td><td><span className="delivered-chip">{o.status}</span></td><td className="number">${o.total.toFixed(2)}</td></tr>):[['#ORD-9932','Oct 24, 2023','Delivered','$249.99'],['#ORD-9841','Sep 12, 2023','Delivered','$89.50'],['#ORD-9710','Aug 05, 2023','Refunded','$120.00'],['#ORD-9502','Jun 28, 2023','Delivered','$450.25']].map(r=><tr key={r[0]}><td className="mono">{r[0]}</td><td>{r[1]}</td><td><span className={r[2]==='Refunded'?'refunded-chip':'delivered-chip'}>{r[2]}</span></td><td className="number">{r[3]}</td></tr>)}</tbody></table></section>
 <aside className="customer-side"><section className="card customer-info"><h2>♙ Personal Information</h2><div className="info-grid"><div><span>FULL NAME</span><p>{customer.name}</p></div><div><span>EMAIL</span><p>{customer.email}</p></div><div><span>PHONE</span><p>{customer.phone||'+1 (555) 123-4567'}</p></div><div><span>DATE OF BIRTH</span><p>May 12, 1990</p></div><div><span>GENDER</span><p>Female</p></div><div><span>LANGUAGE</span><p>English (US)</p></div></div><hr/><span className="mini-label">MARKETING PREFERENCES</span><div><span className="marketing-chip">EMAIL</span><span className="marketing-chip">SMS</span></div></section><section className="card saved-address"><h2><MapPin/>Saved Addresses</h2><div><span className="address-chip">DEFAULT BILLING & SHIPPING</span><b>{customer.name}</b><p>{customer.address||'1234 Silicon Valley Blvd\nSuite 500\nSan Francisco, CA 94107\nUnited States'}</p></div><button>＋ Add New Address</button></section><section className="card internal-notes"><h2>▧ Internal Notes</h2><div className="notes-box"><b>Oct 25: Customer requested expedited shipping for future orders over $200. Marked account accordingly.</b><br/><br/><b>Sep 15: Contacted support regarding missing item in ORD-9841. Issue resolved, item shipped separately.</b></div><label><textarea placeholder="Add a note..."/><Send/></label></section></aside></div></main>;
}