import { useState } from 'react';
import { CalendarDays, ChevronDown, MoreHorizontal } from 'lucide-react';
import { ExportButton } from '../../components/ui/export-button';
import { DropdownMenu, DropdownMenuContent, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuTrigger } from '../../components/ui/dropdown-menu';
import { useStore } from '../../data/store';

const ranges=['Last 7 Days','Last 30 Days','Last 90 Days','This Year'];
export function ReportsPage(){
 const {data}=useStore(); const [range,setRange]=useState('Last 30 Days'); const revenue=data.orders.reduce((a,o)=>a+o.total,0),aov=revenue/Math.max(1,data.orders.length); const bars=[20,30,25,40,35,47.5];
 return <main className="figma-page reports-figma"><div className="figma-page-heading reports-heading"><div><h1>Analytics Overview</h1><p>Track your key performance indicators and revenue trends.</p></div><div className="page-actions"><DropdownMenu><DropdownMenuTrigger asChild><button><CalendarDays/>{range}<ChevronDown className="button-chevron"/></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuRadioGroup value={range} onValueChange={setRange}>{ranges.map(item=><DropdownMenuRadioItem value={item} key={item}>{item}</DropdownMenuRadioItem>)}</DropdownMenuRadioGroup></DropdownMenuContent></DropdownMenu><ExportButton data={data.orders} filename="commercepro-report.csv"/></div></div>
 <div className="report-kpis"><article><span>TOTAL SALES</span><strong>${Math.max(revenue,124563).toLocaleString(undefined,{minimumFractionDigits:2})}</strong><small className="up">↗ +14.5%</small><em>vs last month</em></article><article><span>CONVERSIONS</span><strong>3.24%</strong><small className="up">↗ +0.8%</small><em>vs last month</em></article><article><span>AVG ORDER VALUE</span><strong>${Math.max(aov,85.2).toFixed(2)}</strong><small className="down">↘ -2.1%</small><em>vs last month</em></article></div>
 <div className="reports-grid"><section className="card monthly-card"><div className="section-title"><h2>Monthly Revenue</h2><MoreHorizontal/></div><div className="monthly-chart"><div className="report-y"><span>$50k</span><span>$40k</span><span>$30k</span><span>$20k</span><span>$10k</span><span>0</span></div><div className="report-bars">{bars.map((v,i)=><div key={i}><i className={i===5?'current':''} style={{height:`${v*4.1}px`}}/><span className={i===5?'current-label':''}>{['Jan','Feb','Mar','Apr','May','Jun'][i]}</span></div>)}</div></div></section>
 <section className="card categories-card"><div className="section-title"><h2>Top Categories</h2><button className="bare linkish">View All</button></div><table><thead><tr><th>CATEGORY</th><th>REVENUE</th><th>TREND</th></tr></thead><tbody>{[['▣','Electronics','$45,230','↑ 12%'],['♧','Apparel','$32,100','↑ 8%'],['▤','Home Goods','$28,450','↓ 3%'],['⚒','Sports','$18,783','↑ 5%']].map((r,i)=><tr key={r[1]}><td><span className="category-icon">{r[0]}</span>{r[1]}</td><td className="mono">{r[2]}</td><td className={i===2?'negative':'positive'}>{r[3]}</td></tr>)}</tbody></table></section></div></main>;
}
